import "@coinbase/onchainkit/styles.css";
import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const oldschoolGrotesk = localFont({
  src: [
    {
      path: "./fonts/oldschool-grotesk-font/OldschoolGrotesk-NormalLight.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/oldschool-grotesk-font/OldschoolGrotesk-NormalRegular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/oldschool-grotesk-font/OldschoolGrotesk-NormalMedium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/oldschool-grotesk-font/OldschoolGrotesk-NormalBold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/oldschool-grotesk-font/OldschoolGrotesk-NormalExtraBold.otf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-oldschool",
  display: "swap",
  preload: true,
});
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Flooor FUN",
  description:
    "Generated by `create-onchain`, a Next.js template for OnchainKit",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={oldschoolGrotesk.variable}>
      <body className={`${oldschoolGrotesk.className} bg-background dark`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
